# TODO: other metadata? if not then we can just change to hook -> name
# which DAG to execute for each "hook"
hook_dag_map:
  ingress:
    dag_name: ingress

  egress:
    dag_name: egress

# what types of processing_nodes -- effectively a template
processing_node_types:
  1:
    name: 'attribute_match'
    info: 'match an attribute against a set of values'
    info_url: http://someplace.com
    # this fragment has the effect of setting a "domain DAG name"
    fragment_func: attribute_match
    # this is what the args are, and potentially how to resolve them (look it up)
    fragment_spec:
      # this is a thing that will be passed a key to lookup the value
      attribute:
        # TODO: is this needed? the key is already there...
        name: 'a readable name'
        info: 'name of the attribute to match'
        type: string
      # this just gets a value-- just use it
      values:
        # TODO: is this needed? the key is already there...
        name: 'a readable name'
        info: 'list of values to match against'
        type: list  # TODO: define type of values?
         # this means that the value you are passed will be a key to lookup in options
        is_option_data: true
  2:
    name: 'execute_dynamic_dag'
    info: 'execute another dag'
    fragment_func: execute_dynamic_dag
    fragment_spec:
      # this is a thing that will be passed a key to lookup the value
      dag_prefix:
        # TODO: is this needed? the key is already there...
        name: 'a readable name'
        info: 'string prefix'
        type: string
      # this just gets a value-- just use it
      suffix_key:
        # TODO: is this needed? the key is already there...
        name: 'a readable name'
        info: 'list of values to match against'
        type: string
  3:
    name: 'set_attribute'
    info: 'set an attribute'
    fragment_func: set_attribute
    fragment_spec:
      # this is a thing that will be passed a key to lookup the value
      attribute:
        # TODO: is this needed? the key is already there...
        name: 'a readable name'
        info: 'name of the attribute to match'
        type: string
      # this just gets a value-- just use it
      value:
        # TODO: is this needed? the key is already there...
        name: 'what to set it to'
        info: 'what value to set'
        # TODO: any??
        #type: string

# TODO: add options for max_depth, etc. for DAG validation and execution
# all the DAGs
dags:
  ingress:
    starting_node: 1
    # this should be "option_data" in the "hook_dag_map", so that its
    # basically a set of "args" to the dag
    option_data:
      valid_domains:
        - a.com
        - b.com
        - localhost:8888
      valid_paths: ['/foo/bar', '/foo']
      foo:
        type: int
        value: 1234
    # THIS is not layered
    processing_nodes:
      1: # node instance
        type_id: 1
        args:
          # TODO: make this match up with the global lookup thingy (might switch with values)
          attribute: 'state.pristine_request.headers.Host'
          # TODO: also support lookaside in this same namespace
          values: 'valid_domains'
        outlets:
          true: 2
          false: 3
      2: # node instance
        type_id: 2
        args:
          dag_prefix: dynamic_domain
          suffix_key: 'state.pristine_request.headers.Host'
      3:
        type_id: 3
        args:
          attribute: state.response.body
          value: "not found!"
        outlets:
          true: 4
      4:
        type_id: 3
        args:
          attribute: state.response.code
          value: 404
  egress:
    starting_node: 1
    processing_nodes:
      1: # node instance
        type_id: 3
        args:
          attribute: 'state.response.headers.foo'
          value: 'bar'

  # per domain
  dynamic_domain_localhost:8888:
    starting_node: 1
    processing_nodes:
      1:
        type_id: 1
        args:
          attribute: 'state.pristine_request.path'
          values: 'valid_paths'
        outlets:
          true: 2
          false: 4
      2:
        type_id: 3
        args:
          attribute: "state.response.body"
          value: "found!"
        outlets:
          true: 3
      3:
        type_id: 3
        args:
          attribute: "state.response.code"
          value: 200
      4:
        type_id: 3
        args:
          attribute: "state.request.headers.Host"
          value: "foo.com"
